[package]
name = "documentdb-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
mongodb = "3.0"
tokio = {version = "1", features = ["full"]}
aws-config = "1.0"
aws-sdk-secretsmanager = "1.0"
serde_json = "1.0"
serde = "1.0"
